package com.micromax.bugtracker;

// Generated Sep 28, 2015 4:35:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
/**
 * AddFavourate generated by hbm2java
 */
@SuppressWarnings("restriction")
@Entity
@Table(name = "add_favouraite")
/*@XmlRootElement(name = "addFavourate")*/
public class AddFavouraite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8826994836781499446L;
	private Integer id;
	private Issue issue;
	private String commentedBy;
	private Date createdTime;
	private String columnName1;
	private String columnName2;
	private String columnName3;
	private String columnName4;
	private String columnName5;
	private User user;
	public AddFavouraite() {
	}

	public AddFavouraite(Date createdTime) {
		this.createdTime = createdTime;
	}

	public AddFavouraite(Issue issue, String commentedBy, Date createdTime,
			String columnName1, String columnName2, String columnName3,
			String columnName4, String columnName5,User user) {
		this.issue = issue;
		this.commentedBy = commentedBy;
		this.createdTime = createdTime;
		this.columnName1 = columnName1;
		this.columnName2 = columnName2;
		this.columnName3 = columnName3;
		this.columnName4 = columnName4;
		this.columnName5 = columnName5;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "adfv_id")
	@JsonIgnore
	public Issue getIssue() {
		return this.issue;
	}

	public void setIssue(Issue issue) {
		this.issue = issue;
	}

	
	@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="user_id")
	@JsonIgnore
    public User getUser() {
        return this.user;
    }
	
	public void setUser(User user){
		this.user = user;
	}
	
	
	@Column(name = "commented_by", length = 256)
	public String getCommentedBy() {
		return this.commentedBy;
	}

	public void setCommentedBy(String commentedBy) {
		this.commentedBy = commentedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "columnName1", length = 256)
	public String getColumnName1() {
		return this.columnName1;
	}

	public void setColumnName1(String columnName1) {
		this.columnName1 = columnName1;
	}

	@Column(name = "columnName2", length = 256)
	public String getColumnName2() {
		return this.columnName2;
	}

	public void setColumnName2(String columnName2) {
		this.columnName2 = columnName2;
	}

	@Column(name = "columnName3", length = 256)
	public String getColumnName3() {
		return this.columnName3;
	}

	public void setColumnName3(String columnName3) {
		this.columnName3 = columnName3;
	}

	@Column(name = "columnName4", length = 256)
	public String getColumnName4() {
		return this.columnName4;
	}

	public void setColumnName4(String columnName4) {
		this.columnName4 = columnName4;
	}

	@Column(name = "columnName5", length = 256)
	public String getColumnName5() {
		return this.columnName5;
	}

	public void setColumnName5(String columnName5) {
		this.columnName5 = columnName5;
	}

}
