package com.micromax.bugtracker;

// Generated Sep 28, 2015 4:35:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AttachementFile generated by hbm2java
 */
@SuppressWarnings("restriction")
@Entity
@Table(name = "attachement_file")
/*@XmlRootElement(name = "attachement")*/
public class AttachementFile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8686470366070386747L;
	private AttachementFileId id;
	private Issue issue;
	private String fileName;
	private String filePath;
	private Date createdTime;
	private String columnName1;
	private String columnName2;
	private String columnName3;
	private String columnName4;
	private String columnName5;
	private User user;

	public AttachementFile() {
	}

	public AttachementFile(AttachementFileId id, Issue issue, Date createdTime) {
		this.id = id;
		this.issue = issue;
		this.createdTime = createdTime;
	}

	public AttachementFile(AttachementFileId id, Issue issue, String fileName,
			String filePath, Date createdTime, String columnName1,
			String columnName2, String columnName3, String columnName4,
			String columnName5,User user) {
		this.id = id;
		this.issue = issue;
		this.fileName = fileName;
		this.filePath = filePath;
		this.createdTime = createdTime;
		this.columnName1 = columnName1;
		this.columnName2 = columnName2;
		this.columnName3 = columnName3;
		this.columnName4 = columnName4;
		this.columnName5 = columnName5;
		this.user = user;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public AttachementFileId getId() {
		return this.id;
	}

	public void setId(AttachementFileId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	@JsonIgnore
	public Issue getIssue() {
		return this.issue;
	}

	public void setIssue(Issue issue) {
		this.issue = issue;
	}

	@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
	@JsonIgnore
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
	
	@Column(name = "file_name", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_path", length = 65535)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "columnName1", length = 256)
	public String getColumnName1() {
		return this.columnName1;
	}

	public void setColumnName1(String columnName1) {
		this.columnName1 = columnName1;
	}

	@Column(name = "columnName2", length = 256)
	public String getColumnName2() {
		return this.columnName2;
	}

	public void setColumnName2(String columnName2) {
		this.columnName2 = columnName2;
	}

	@Column(name = "columnName3", length = 256)
	public String getColumnName3() {
		return this.columnName3;
	}

	public void setColumnName3(String columnName3) {
		this.columnName3 = columnName3;
	}

	@Column(name = "columnName4", length = 256)
	public String getColumnName4() {
		return this.columnName4;
	}

	public void setColumnName4(String columnName4) {
		this.columnName4 = columnName4;
	}

	@Column(name = "columnName5", length = 256)
	public String getColumnName5() {
		return this.columnName5;
	}

	public void setColumnName5(String columnName5) {
		this.columnName5 = columnName5;
	}

}
