package com.micromax.bugtracker;

// Generated Sep 28, 2015 4:35:12 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttachementFileId generated by hbm2java
 */
@Embeddable
public class AttachementFileId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 151030356876756954L;
	private int id;
     private int userId;

    public AttachementFileId() {
    }

    public AttachementFileId(int id, int userId) {
       this.id = id;
       this.userId = userId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttachementFileId) ) return false;
		 AttachementFileId castOther = ( AttachementFileId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


