package com.micromax.bugtracker;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.metamodel.binding.CascadeType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * PrivateMessages generated by hbm2java
 */
@Entity
@Table(name="private_messages")
public class PrivateMessages  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7187262111279569210L;
	private int id;
     private Issue issue;
     private String fkUid;
     private String toId;
     private String bcc;
     private Date createDate;
     private String messageBody;
     private User user;
     private String coulmn2;
     private String column3;
     private String column4;
     private String column5;
     private String ccId;
     private Set<MessageReadbleStatus> messageReadbleStatuses = new HashSet<MessageReadbleStatus>(0);
    public PrivateMessages() {
    }

	
    public PrivateMessages(int id) {
        this.id = id;
    }
    public PrivateMessages(int id, String fkUid, String toId, String bcc, Date createDate, 
    		String messageBody,Issue issue, User user, String coulmn2, String column3, String column4, String column5,String ccId,Set<MessageReadbleStatus> messageReadbleStatuses) {
       this.id = id;
       this.fkUid = fkUid;
       this.toId = toId;
       this.bcc = bcc;
       this.createDate = createDate;
       this.messageBody = messageBody;
       this.user = user;
       this.issue = issue;
       this.coulmn2 = coulmn2;
       this.column3 = column3;
       this.column4 = column4;
       this.column5 = column5;
       this.ccId = ccId;
       this.messageReadbleStatuses = messageReadbleStatuses;
    }
   
    @Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }
    
     @ManyToOne(fetch=FetchType.EAGER)
     @JoinColumn(name="issue_id")
     @JsonIgnore
     public Issue getIssue() {
         return this.issue;
     }
     
     public void setIssue(Issue issue) {
         this.issue = issue;
     }
     
     
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="fk_uid", length=256)
    public String getFkUid() {
        return this.fkUid;
    }
    
    public void setFkUid(String fkUid) {
        this.fkUid = fkUid;
    }

    
    @Column(name="to_id", length=256)
    public String getToId() {
        return this.toId;
    }
    
    public void setToId(String toId) {
        this.toId = toId;
    }

    
    @Column(name="bcc", length=256)
    public String getBcc() {
        return this.bcc;
    }
    
    public void setBcc(String bcc) {
        this.bcc = bcc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="message_body")
    public String getMessageBody() {
        return this.messageBody;
    }
    
    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="from_id")
	@JsonIgnore
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="coulmn2", length=45)
    public String getCoulmn2() {
        return this.coulmn2;
    }
    
    public void setCoulmn2(String coulmn2) {
        this.coulmn2 = coulmn2;
    }

    
    @Column(name="column3", length=45)
    public String getColumn3() {
        return this.column3;
    }
    
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    
    @Column(name="column4", length=45)
    public String getColumn4() {
        return this.column4;
    }
    
    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    
    @Column(name="column5", length=45)
    public String getColumn5() {
        return this.column5;
    }
    
    public void setColumn5(String column5) {
        this.column5 = column5;
    }
    
    @Column(name="cc_id", length=45)
    public String getCcId() {
        return this.ccId;
    }
    
    public void setCcId(String ccId) {
        this.ccId = ccId;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="privateMessages")
    public Set<MessageReadbleStatus> getMessageReadbleStatuses() {
        return this.messageReadbleStatuses;
    }
    
    public void setMessageReadbleStatuses(Set<MessageReadbleStatus> messageReadbleStatuses) {
        this.messageReadbleStatuses = messageReadbleStatuses;
    }


}


