package com.micromax.bugtracker;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.OneToMany;
/**
 * ProdVersion generated by hbm2java
 */
@Entity
@Table(name="prod_version")
public class ProdVersion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5198245353550497998L;
	private Integer id;
     private Category category;
     private String productVersion;
     private String column1;
     private String column2;
     private String column3;
     private String column4;
     private String column5;
     private Set<Issue> issues = new HashSet<Issue>(0);
    public ProdVersion() {
    }

    
	
    public ProdVersion(int id, String productVersion) {
		super();
		this.id = id;
		this.productVersion = productVersion;
	}



	public ProdVersion(int id) {
        this.id = id;
    }
    public ProdVersion(Integer id, 
    		Category category, 
    		String productVersion, 
    		String column1, 
    		String column2, 
    		String column3, 
    		String column4, 
    		String column5) {
       this.id = id;
       this.category = category;
       this.productVersion = productVersion;
       this.column1 = column1;
       this.column2 = column2;
       this.column3 = column3;
       this.column4 = column4;
       this.column5 = column5;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ct_id")
    @JsonIgnore
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="product_version", length=45)
    public String getProductVersion() {
        return this.productVersion;
    }
    
    public void setProductVersion(String productVersion) {
        this.productVersion = productVersion;
    }

    
    @Column(name="column1", length=45)
    public String getColumn1() {
        return this.column1;
    }
    
    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    
    @Column(name="column2", length=45)
    public String getColumn2() {
        return this.column2;
    }
    
    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    
    @Column(name="column3", length=45)
    public String getColumn3() {
        return this.column3;
    }
    
    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    
    @Column(name="column4", length=45)
    public String getColumn4() {
        return this.column4;
    }
    
    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    
    @Column(name="column5", length=45)
    public String getColumn5() {
        return this.column5;
    }
    
    public void setColumn5(String column5) {
        this.column5 = column5;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "prodVersion")
	public Set<Issue> getIssues() {
		return this.issues;
	}

	public void setIssues(Set<Issue> issues) {
		this.issues = issues;
	}


}


