package com.micromax.bugtracker;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user", uniqueConstraints = @UniqueConstraint(columnNames="emailid"))
public class User  implements java.io.Serializable {


     private int id;
     private String emailId;
     private Byte isPrivateMessageEnable;
     private Set<PrivateMessages> privateMessageses = new HashSet<PrivateMessages>(0);
     private Set<UserComment> userComments = new HashSet<UserComment>(0);
     private Set<Issue> issues = new HashSet<Issue>(0);
     private Set<Fallow> fallows = new HashSet<Fallow>(0);
     private Set<AttachementFile> attachementFiles = new HashSet<AttachementFile>(0);
     private Set<AddFavouraite> addFavouraites = new HashSet<AddFavouraite>(0);
     private Set<ReportFlag> reportFlags = new HashSet<ReportFlag>(0);
    public User() {
    }

	
    public User(int id) {
        this.id = id;
    }
    
    public User(int id,String emailId){
    	this.id  = id;
    	this.emailId = emailId;
    }
    public User(int id, String emailId, Set<UserComment> userComments,Set<Issue> issues, Set<Fallow> fallows,
            Set<AttachementFile> attachementFiles, Set<AddFavouraite> addFavouraites, Set<ReportFlag> reportFlags,Set<PrivateMessages> privateMessageses) {
       this.id = id;
       this.emailId = emailId;
       this.userComments = userComments;
       this.issues = issues;
       this.fallows = fallows;
       this.attachementFiles = attachementFiles;
       this.addFavouraites = addFavouraites;
       this.reportFlags = reportFlags;
       this.privateMessageses = privateMessageses;
    }
   
    @Id     
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="emailid", unique=true, length=256)
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="user")
    public Set<UserComment> getUserComments() {
        return this.userComments;
    }
    
    public void setUserComments(Set<UserComment> userComments) {
        this.userComments = userComments;
    }

    
    @OneToMany(fetch=FetchType.EAGER, mappedBy="user")
    public Set<Issue> getIssues() {
        return this.issues;
    }
    
    public void setIssues(Set<Issue> issues) {
        this.issues = issues;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="user")
    public Set<Fallow> getFallows() {
        return this.fallows;
    }
    
    public void setFallows(Set<Fallow> fallows) {
        this.fallows = fallows;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="user")
    public Set<AttachementFile> getAttachementFiles() {
        return this.attachementFiles;
    }
    
    public void setAttachementFiles(Set<AttachementFile> attachementFiles) {
        this.attachementFiles = attachementFiles;
    }


    @OneToMany(fetch=FetchType.EAGER, mappedBy="user")
    public Set<AddFavouraite> getAddFavouraites() {
        return this.addFavouraites;
    }
    
    public void setAddFavouraites(Set<AddFavouraite> addFavouraites) {
        this.addFavouraites = addFavouraites;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="user")
    public Set<ReportFlag> getReportFlags() {
        return this.reportFlags;
    }
    
    public void setReportFlags(Set<ReportFlag> reportFlags) {
        this.reportFlags = reportFlags;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="user")
    public Set<PrivateMessages> getPrivateMessageses() {
        return this.privateMessageses;
    }
    
    public void setPrivateMessageses(Set<PrivateMessages> privateMessageses) {
        this.privateMessageses = privateMessageses;
    }
    
    @Column(name="is_private_message_enable")
	public Byte getIsPrivateMessageEnable() {
		return isPrivateMessageEnable;
	}


	public void setIsPrivateMessageEnable(Byte isPrivateMessageEnable) {
		this.isPrivateMessageEnable = isPrivateMessageEnable;
	}

    


}


