package com.micromax.bugtracker;

// Generated Sep 28, 2015 4:35:12 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserComment generated by hbm2java
 */
@Entity
@Table(name = "user_comment")
/*@XmlRootElement(name = "usercomment")*/
public class UserComment implements java.io.Serializable {

	private Integer id;
	private Issue issue;
	private User user;
	//private String commentedBy;
	private String description;
	private Date createdTime;
	private String columnName1;
	private String columnName2;
	private String columnName3;
	private String columnName4;
	private String columnName5;

	public UserComment() {
	}

	public UserComment(Date createdTime) {
		this.createdTime = createdTime;
	}

	public UserComment(Issue issue,String description,
			Date createdTime, String columnName1, String columnName2,User user,
			String columnName3, String columnName4, String columnName5) {
		this.issue = issue;
		//this.commentedBy = commentedBy;
		this.description = description;
		this.createdTime = createdTime;
		this.columnName1 = columnName1;
		this.columnName2 = columnName2;
		this.columnName3 = columnName3;
		this.columnName4 = columnName4;
		this.columnName5 = columnName5;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	
	@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="commented_by")
	@JsonIgnore
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "is_id")
	@JsonIgnore
	public Issue getIssue() {
		return this.issue;
	}

	public void setIssue(Issue issue) {
		this.issue = issue;
	}

	

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_time",length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "columnName1", length = 256)
	public String getColumnName1() {
		return this.columnName1;
	}

	public void setColumnName1(String columnName1) {
		this.columnName1 = columnName1;
	}

	@Column(name = "columnName2", length = 256)
	public String getColumnName2() {
		return this.columnName2;
	}

	public void setColumnName2(String columnName2) {
		this.columnName2 = columnName2;
	}

	@Column(name = "columnName3", length = 256)
	public String getColumnName3() {
		return this.columnName3;
	}

	public void setColumnName3(String columnName3) {
		this.columnName3 = columnName3;
	}

	@Column(name = "columnName4", length = 256)
	public String getColumnName4() {
		return this.columnName4;
	}

	public void setColumnName4(String columnName4) {
		this.columnName4 = columnName4;
	}

	@Column(name = "columnName5", length = 256)
	public String getColumnName5() {
		return this.columnName5;
	}

	public void setColumnName5(String columnName5) {
		this.columnName5 = columnName5;
	}

}
